version: '3.7'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    env_file:
      - database.env # configure postgres
    volumes:
      - postgres:/data/postgres
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - prod-todo
    restart: unless-stopped

networks:
  prod-todo:
    driver: bridge

volumes:
  postgres:
